export const sinksCatalog = {
  handmadeSinks: [
    {
      size: "24x18",
      bowl: "Single",
      finish: ["Matt", "Nano Black", "Gold", "Mirror", "Rosegold"],
      features: ["Taphole"],
    },
    {
      size: "18x16",
      bowl: "Single",
      finish: ["Matt", "Nano Black"],
      features: [],
    },
    { size: "20x17", bowl: "Single", finish: ["Matt"], features: [] },
    { size: "21x18", bowl: "Single", finish: ["Matt"], features: [] },
    { size: "22x18", bowl: "Single", finish: ["Matt"], features: [] },
    { size: "27x20", bowl: "Single", finish: ["Matt"], features: [] },
    { size: "24x24", bowl: "Single", finish: ["Matt"], features: [] },
    { size: "30x18", bowl: "Single", finish: ["Matt"], features: [] },
    { size: "32x20", bowl: "Single", finish: ["Matt"], features: [] },
    { size: "32x18", bowl: "Double", finish: ["Matt"], features: [] },
    {
      size: "37x18",
      bowl: "Double",
      finish: ["Matt", "Nano Black"],
      features: ["Taphole", "Drainboard"],
    },
    {
      size: "45x20",
      bowl: "Double",
      finish: ["Matt", "Nano Black"],
      features: ["Taphole", "Drainboard"],
    },
    {
      size: "37x18",
      bowl: "Single",
      finish: ["Matt"],
      features: ["Drainboard"],
    },
    {
      size: "45x20",
      bowl: "Single",
      finish: ["Matt"],
      features: ["Drainboard"],
    },
  ],
  waterfallSinks: [
    {
      size: "30x18",
      finish: "Nano Black",
      features: [
        "Waterfall Faucet",
        "Glass Washer",
        "Soap Dispenser",
        "RO Tap",
        "Chopping Board",
        "Triangle Basket",
        "Square Basket",
        "Coupling Set",
      ],
    },
    {
      size: "24x18",
      finish: "Nano Black",
      features: [
        "Waterfall Faucet",
        "Glass Washer",
        "Soap Dispenser",
        "RO Tap",
        "Chopping Board",
        "Triangle Basket",
        "Square Basket",
        "Coupling Set",
      ],
    },
    {
      size: "46x18",
      finish: "Nano Black",
      bowl: "Double",
      features: ["All inclusions"],
    },
    {
      size: "37x18",
      finish: "Nano Black",
      bowl: "Double",
      features: ["All inclusions"],
    },
    {
      size: "30x18 Piano Button",
      finish: "Nano Black",
      features: ["All inclusions"],
    },
  ],

  grade304Sinks: [
    { size: "24x18", bowl: "Single", finish: "Matt", features: [] },
    { size: "37x18", bowl: "Double", finish: "Matt", features: [] },
    { size: "45x20", bowl: "Double", finish: "Matt", features: [] },
    { size: "24x18", bowl: "Single", finish: "Matt", features: ["Taphole"] },
    { size: "37x18", bowl: "Double", finish: "Matt", features: ["Taphole"] },
    { size: "45x20", bowl: "Double", finish: "Matt", features: ["Taphole"] },
    { size: "30x18", bowl: "Single", finish: "Matt", features: [] },
    { size: "18x16", bowl: "Single", finish: "Matt", features: [] },
  ],
  singleBowlSteel: [
    { code: "IN0010", size: "20x17 20*18", weightKg: 2.4, polish: "Glossy" },
    { code: "IN0011", size: "22x18 24*18", weightKg: 1.6, polish: "Glossy" },
    { code: "IN0012", size: "22x18 24*18", weightKg: 2.1, polish: "Glossy" },
    { code: "IN0013", size: "22x18 24*18", weightKg: 2.4, polish: "Glossy" },
    { code: "IN0014", size: "22x18 24*18", weightKg: 3.1, polish: "Glossy" },
    { code: "IN0015", size: "22x18 24*18", weightKg: 3.1, polish: "Glossy" },
  ],

  doubleBowlSteel: [
    {
      code: "IN0017",
      size: "37x18",
      weightKg: 3.0,
      polish: "Glossy",
      notes: "Circular drains",
    },
    {
      code: "IN0018",
      size: "37x18",
      weightKg: 4.0,
      polish: "Glossy",
      notes: "Circular drains",
    },
    {
      code: "IN0019",
      size: "37x18",
      weightKg: 4.0,
      polish: "Glossy",
      notes: "Square bowl, back coating",
    },
  ],

  indianSinks: [
    {
      code: "IN0001",
      size: "14x16",
      bowl: "Single",
      weightKg: 1.0,
      material: "Stainless Steel",
      polish: "Glossy",
      features: ["Circular Drain"],
    },
  ],
  ptmtTaps: [
    {
      code: "PT001",
      model: "Long Body Tap",
      type: "Pillar Tap",
      material: "PTMT",
      finish: "White",
      features: ["Long Spout", "Smooth Water Flow", "Easy Installation"],
    },
  ],
};
