export const sinksCatalog = {
  handmadeSinks: [
    {
      size: "24x18",
      bowl: "Single",
      finish: ["Matt", "Nano Black", "Gold", "Mirror", "Rose Gold"],
      features: [],
    },
    {
      size: "24x18",
      bowl: "Single",
      finish: ["Matt", "Nano Black"],
      features: ["Taphole"],
    },
    {
      size: "18x16",
      bowl: "Single",
      finish: ["Matt", "Nano Black"],
      features: [],
    },
    { size: "20x17", bowl: "Single", finish: ["Matt"], features: [] },
    { size: "21x18", bowl: "Single", finish: ["Matt"], features: [] },
    { size: "22x18", bowl: "Single", finish: ["Matt"], features: [] },
    {
      size: "37x18",
      bowl: "Double",
      finish: ["Matt", "Nano Black"],
      features: [],
    },
    {
      size: "37x18",
      bowl: "Double",
      finish: ["Matt", "Nano Black"],
      features: ["Taphole"],
    },
    {
      size: "37x18",
      bowl: "Single",
      finish: ["Matt"],
      features: ["Drainboard"],
    },
    {
      size: "45x20",
      bowl: "Double",
      finish: ["Matt", "Nano Black"],
      features: [],
    },
    {
      size: "45x20",
      bowl: "Double",
      finish: ["Matt", "Nano Black"],
      features: ["Taphole"],
    },
    {
      size: "45x20",
      bowl: "Single",
      finish: ["Matt"],
      features: ["Drainboard"],
    },
    { size: "30x18", bowl: "Single", finish: ["Matt"], features: [] },
    { size: "32x20", bowl: "Single", finish: ["Matt"], features: [] },
    { size: "32x18", bowl: "Double", finish: ["Matt"], features: [] },
    { size: "27x20", bowl: "Single", finish: ["Matt"], features: [] },
    { size: "24x24", bowl: "Single", finish: ["Matt"], features: [] },
  ],

  indianSinks: [
    { size: "14x16", bowl: "Single", weightKg: 1000, finish: "Glossy" },
    { size: "15x12", bowl: "Single", weightKg: 1000, finish: "Glossy" },
    { size: "18x16", bowl: "Single", weightKg: 1200, finish: "Glossy" },
    { size: "20x17", bowl: "Single", weightKg: 2400, finish: "Glossy" },
    { size: "21x18", bowl: "Single", weightKg: 2400, finish: "Glossy" },
    { size: "22x18", bowl: "Single", weightKg: 1600, finish: "Glossy" },
    { size: "22x18", bowl: "Single", weightKg: 2100, finish: "Glossy" },
    { size: "22x18", bowl: "Single", weightKg: 2400, finish: "Glossy" },
    { size: "22x18", bowl: "Single", weightKg: 2700, finish: "Glossy" },
    { size: "22x18", bowl: "Single", weightKg: 3100, finish: "Glossy" },
    { size: "24x18", bowl: "Single", weightKg: 1600, finish: "Glossy" },
    { size: "24x18", bowl: "Single", weightKg: 2100, finish: "Glossy" },
    { size: "24x18", bowl: "Single", weightKg: 2400, finish: "Glossy" },
    { size: "24x18", bowl: "Single", weightKg: 2700, finish: "Glossy" },
    { size: "24x18", bowl: "Single", weightKg: 3100, finish: "Glossy" },
    {
      size: "22x18",
      bowl: "Single",
      weightKg: 3100,
      finish: "Glossy",
      features: ["Square bowl back coating"],
    },
    {
      size: "24x18",
      bowl: "Single",
      finish: "Glossy",
      features: ["Square bowl back coating"],
    },
    { size: "37x18", bowl: "Double", weightKg: 3000, finish: "Glossy" },
    {
      size: "37x18",
      bowl: "Double",
      weightKg: 4000,
      finish: "Glossy",
    },
    {
      size: "37x18",
      bowl: "Double",
      weightKg: 4000,
      finish: "Glossy",
      features: ["Square bowl back coating"],
    },
  ],

  grade304Sinks: [
    { size: "24x18", finish: "Matt", features: [] },
    { size: "24x18", finish: "Matt", features: ["Taphole"] },
    { size: "37x18", finish: "Matt", features: [] },
    { size: "37x18", finish: "Matt", features: ["Taphole"] },
    { size: "45x20", finish: "Matt", features: [] },
    { size: "45x20", finish: "Matt", features: ["Taphole"] },
    { size: "30x18", bowl: "Single", finish: "Matt", features: [] },
    { size: "18x16", finish: "Matt", features: [] },
  ],

  waterfallSinks: [
    {
      size: "24x18",
      bowl: "Single",
      finish: "Nano Black",
      features: [
        "Waterfall Faucet",
        "Glass Washer",
        "Soap Dispenser",
        "RO Tap",
        "Chopping Board",
        "Triangle Basket",
        "Square Basket",
        "Coupling Set",
      ],
    },
    {
      size: "30x18",
      bowl: "Single",
      finish: "Nano Black",
      features: [
        "Waterfall Faucet",
        "Glass Washer",
        "Soap Dispenser",
        "RO Tap",
        "Chopping Board",
        "Triangle Basket",
        "Square Basket",
        "Coupling Set",
      ],
    },
    {
      size: "30x18",
      bowl: "Single",
      finish: "Nano Black",
      features: [
        "Piano Button",
        "Waterfall Faucet",
        "Glass Washer",
        "Soap Dispenser",
        "RO Tap",
        "Chopping Board",
        "Triangle Basket",
        "Square Basket",
        "Coupling Set",
      ],
    },

    {
      size: "46x18",
      bowl: "Double",
      finish: "Nano Black",
      features: [
        "Waterfall Faucet",
        "Glass Washer",
        "Soap Dispenser",
        "RO Tap",
        "Chopping Board",
        "Triangle Basket",
        "Square Basket",
        "Coupling Set",
      ],
    },
    {
      size: "37x18",
      bowl: "Double",
      finish: "Nano Black",
      features: [
        "Waterfall Faucet",
        "Glass Washer",
        "Soap Dispenser",
        "RO Tap",
        "Chopping Board",
        "Triangle Basket",
        "Square Basket",
        "Coupling Set",
      ],
    },
  ],

  ptmtTaps: [
    { range: "Long body" },
    { range: "Bib cock" },
    { range: "Angel wall" },
    { range: "Pillar cock" },
    { range: "Nozzle cock" },
    { range: "Washing cock" },
    { range: "Sink cock" },
    { range: "Swan neck" },
    { range: "2 in 1 A/W" },
    { range: "2 in 1 B/C" },
    { range: "Centre hole" },
    { range: "Sink mixer" },
    { range: "Wall mixer - L band", size: ["15 mm", "17 mm", "20 mm"] },
  ],
};
